CREATE TABLE IF NOT EXISTS `USER_TABEL`(
    `U_ID` INT UNSIGNED AUTO_INCREMENT,
    `U_NAME` VARCHAR(20) NOT NULL,
    `U_PASSWORD` VARCHAR(30) NOT NULL,
    `U_EMAIL` VARCHAR(500) NOT NULL,
    `U_GROUP` INT UNSIGNED,
    `U_REG_DATE` DATE,
    `T_ID` INT UNSIGNED,
    PRIMARY KEY ( `U_ID` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table IF not exists `LOG_TABEL`(
	`T_ID` INT UNSIGNED AUTO_INCREMENT,
    `LOG_TIME` DATE,
    primary key (`T_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table IF not exists `DATA_TABEL`(
	`D_ID` INT UNSIGNED AUTO_INCREMENT,
    `U_ID` INT UNSIGNED NOT NULL,
    `DATA_TYPE` INT UNSIGNED NOT NULL,
    `STR_DATA` VARCHAR(2500),
    `INT_DATA` INT,
    `FLOAT_DATA` FLOAT,
    primary key (`D_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;